blank_issues_enabled: false
contact_links:
  - name: Common Issues
    url: https://github.com/GeyserMC/Geyser/wiki/Common-Issues
    about: Check the common issues to see if you are not alone with that issue and see how you can fix them.
  - name: Frequently Asked Questions
    url: https://github.com/GeyserMC/Geyser/wiki/FAQ
    about: Look at the FAQ page for answers for frequently asked questions.
  - name: Get help on the GeyserMC Discord server
    url: https://discord.gg/geysermc
    about: If your issue seems like it could possibly be an easy fix due to configuration, please hop on our Discord.
